# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-Server-Ident
version:      0.3
version_from: Ident.pm
installdirs:  site
requires:
    Carp:                          0
    POE:                           0.0607
    Socket:                        0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
