author: Chris Williams <chris@bingosnet.co.uk>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: POE-Component-Server-Ident
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  POE: 0.38
  Socket: 0
  warnings: 0
version: 1.08
